# Generated by Django 4.1 on 2022-08-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool_name',
            new_name='name',
        ),
    ]
