# Generated by Django 4.1 on 2022-08-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_tool_name_tool_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_pic',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
