# Generated by Django 4.1 on 2022-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_temp_instruction_temp_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='temp_num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
