# Generated by Django 4.1 on 2022-08-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_tool_tool_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_pic',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
