# Generated by Django 4.1 on 2022-08-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_instruction_temp_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ManyToManyField(to='recipes.ingredientamount')),
                ('instruction', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.instruction')),
            ],
        ),
    ]
