# Generated by Django 4.1 on 2022-08-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_instructioningredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructioningredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='instructioningredient',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientamount'),
        ),
    ]
