# Generated by Django 4.1 on 2022-08-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, default=0, null=True),
        ),
    ]
