# Generated by Django 4.1 on 2022-08-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_ingr_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_pic',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_pic',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
