# Generated by Django 4.1 on 2022-08-16 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_ingr_pic_alter_tool_tool_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingr_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
        ),
    ]
