# Generated by Django 4.1 on 2022-08-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_instructioningredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructioningredient',
            name='ingredient',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredientamount'),
        ),
    ]
