# Generated by Django 4.1 on 2022-08-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_ingr_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('g', 'Gram'), ('mL', 'Milliliter'), ('L', 'Liter')], default='g', max_length=4),
        ),
    ]
