# Generated by Django 4.1 on 2022-08-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='rec',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
