# Generated by Django 4.1 on 2022-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_instructioningredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructioningredient',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='instructioningredient',
            name='ingredient',
            field=models.ManyToManyField(to='recipes.ingredient'),
        ),
    ]
