# Generated by Django 4.1 on 2022-08-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_instructioningredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructioningredient',
            name='ingredient',
            field=models.ManyToManyField(to='recipes.ingredientamount'),
        ),
    ]
