# Generated by Django 4.1 on 2022-08-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientamount_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('g', 'g'), ('mL', 'mL'), ('L', 'L')], default='g', max_length=4),
        ),
    ]
