# Generated by Django 4.1 on 2022-08-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredientamount_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingr_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingr_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingr_pic',
            new_name='pic',
        ),
    ]
