# Generated by Django 4.1 on 2022-08-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_instructioningredient_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.ManyToManyField(to='recipes.instruction')),
                ('instruction_i', models.ManyToManyField(to='recipes.instructioningredient')),
            ],
        ),
    ]
