# Generated by Django 4.1 on 2022-08-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_instructionall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='time',
            field=models.DurationField(blank=True, default='00:30:00'),
        ),
    ]
