# Generated by Django 4.1 on 2022-08-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_rec_review_recipe_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True)),
                ('ingr', models.TextField(blank=True)),
                ('instr', models.TextField(blank=True)),
            ],
        ),
    ]
