# Generated by Django 4.1 on 2022-08-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_instruction_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='time',
        ),
        migrations.AddField(
            model_name='instruction',
            name='time_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='instruction',
            name='time_unit',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('hr', 'hr'), ('min', 'min'), ('s', 's'), ('overnight', 'Overnight')], default='min', max_length=10),
        ),
    ]
