# Generated by Django 4.1 on 2022-09-04 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_instruction_rec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['step']},
        ),
    ]
