# Generated by Django 4.1 on 2022-08-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_reciperec'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperec',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
