# Generated by Django 4.0.6 on 2022-08-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_reciperec_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tool',
            old_name='tool_pic',
            new_name='pic',
        ),
    ]
