# Generated by Django 4.1 on 2022-09-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_instruction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default=0, upload_to=''),
        ),
    ]
