# Generated by Django 4.1 on 2022-08-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_delete_instructionall'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=1)),
                ('instruct_i', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.instructioningredient')),
                ('instruction', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.instruction')),
            ],
        ),
    ]
