# Generated by Django 4.1 on 2022-08-25 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_instructionstep_instruct_i_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionstep',
            name='instruct_i',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.instructioningredient'),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='instruction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.instruction'),
        ),
    ]
