# Generated by Django 4.1 on 2022-09-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_instruction_options_recipe_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tools',
        ),
    ]
