# Generated by Django 4.1 on 2022-09-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_remove_recipe_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('rec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='SubRecipe', to='recipes.recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='rec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientAmounts', to='recipes.subrecipe'),
        ),
    ]
