# Generated by Django 4.1 on 2022-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_instructionstep_instruct_i_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingr_amount',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.ManyToManyField(to='recipes.instructionstep'),
        ),
    ]
