# Generated by Django 4.1 on 2022-08-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_recipe_ingr_amount_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='topic',
            field=models.CharField(choices=[('Bread', 'Bread'), ('Cake', 'Cake'), ('Cookies', 'Cookies'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
