# Generated by Django 4.1 on 2022-09-11 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_rename_rec_ingredientamount_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('rec', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='IngredientGroup', to='recipes.recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredientamount',
            name='sub',
        ),
        migrations.DeleteModel(
            name='SubRecipe',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientAmounts', to='recipes.ingredientgroup'),
        ),
    ]
