# Generated by Django 4.1 on 2022-09-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_ingredientgroup_remove_ingredientamount_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('g', 'g'), ('kg', 'kg'), ('mL', 'mL'), ('L', 'L')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='rec',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientGroups', to='recipes.recipe'),
        ),
    ]
