# Generated by Django 4.1 on 2022-08-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_ingredientamount_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='simpleInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='unit',
            field=models.CharField(blank=True, choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('g', 'g'), ('mL', 'mL'), ('L', 'L')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='instr',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.simpleinstruction'),
        ),
    ]
