# Generated by Django 4.1 on 2022-08-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_alter_instruction_instr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='instr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.simpleinstruction'),
        ),
    ]
