# Generated by Django 4.1 on 2022-08-25 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_instruction_instr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='instr',
        ),
        migrations.AddField(
            model_name='instruction',
            name='instrc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.simpleinstruction'),
        ),
    ]
