# Generated by Django 4.1 on 2022-08-25 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_remove_instruction_instr_instruction_instrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructioningredient',
            name='instruction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.simpleinstruction'),
        ),
    ]
